### ISSUE TITLE
Imported Photos have no virtual album

### ISSUE THREAD

**Issue by ClaudiaLev** [Piwigo/Flickr2Piwigo#62]
Piwigo 12.1
The import from Flickr is still working, but the photos will not appear in the choosen album.
The photos are not connected to any virtual album after import, so it is needed to do this manually.

**Comment by samwilson** [comment]
Is this still happening with the new version?

With the chosen album, is it an existing one that you've selected, or a new one created via the Flickr import page? i.e. here:

![piwigo-album](https://github.com/Piwigo/Flickr2Piwigo/assets/213655/11b7412e-443b-4718-b60c-3d03866a508c)

**Comment by ClaudiaLev** [comment]
everything is working fine with the new version!
