### ISSUE TITLE
Fatal Error with PHP 8.0.0 and newer

### ISSUE THREAD

**Issue by ClaudiaLev** [Piwigo/Flickr2Piwigo#67]
The plugin Flickr2Piwigo is not working with PHP 8.0.0 and newer 

It connects to Flickr and shows the list of albums.
So the connection to Flickr ist working fine.

Selecting an album leads to an empty site with the following error:

Fatal error: Uncaught Error: Call to undefined function create_function() in /mnt/web116/d2/02/5213002/htdocs/xxxxx/piwigo/plugins/flickr2piwigo/admin/import.php:181
Stack trace: #0 /mnt/web116/d2/02/5213002/htdocs/xxxxx/piwigo/plugins/flickr2piwigo/admin.php(19): include()  /mnt/web116/d2/02/5213002/htdocs/xxxxx/piwigo/admin/plugin.php(53): include_once('...')  /mnt/web116/d2/02/5213002/htdocs/xxxxx/piwigo/admin.php(346): include('...')  {main} thrown in /mnt/web116/d2/02/5213002/htdocs/xxxxx/piwigo/plugins/flickr2piwigo/admin/import.php on line 181 

**The create_function() function has been DEPRECATED as of PHP 7.2.0, and REMOVED as of PHP 8.0.0.
I hope someone can fix this problem.**

**Comment by samwilson** [comment]
Fixed in 1.5.6. Sorry it took so long!
